### ISSUE TITLE
Last graphic code

### ISSUE THREAD

**Issue by paracon** [rstats-tartu/discussion#3]
I could not get the full code for the last graphic we made in class and I could not find it in the EDA folder index.Rmd.

I think it started with:

mean_incidence_year_sex %>%
  filter(Site %in% top_20_sites) %>%
  ggplot(aes(Sex, mean_incidence)) +
  geom_bar(stat = "identity") +

**Comment by tpall** [comment]
The piece of code in your message needs 

`facet_wrap(~ Site)`

Today I updated lecture materials in EDA folder.
Please, have a look for updated materials (including slightly different code to produce this plot) at: https://rstatstartu-eda.netlify.com
